- name: "reboot"
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: "Waiting for host to come back"
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay={{ delay_after_restart }} port={{ ansible_port }}
  become: false