- name: "Enable IPv4 forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: "Start and enable docker service"
  systemd: 
    name: docker
    state: started
    enabled: yes