- name: Conditionally decide to load in variables for vagrant
  include_vars:
    file: vagrant.yml
  when: vagrant

- import_tasks: mount-script.yml
- import_tasks: docker.yml
- import_tasks: samba.yml
- import_tasks: transmission.yml
- import_tasks: streamline.yml